version: '3.4'
services:
    test-app:
        build: .
        restart: unless-stopped
        container_name: test-app
        entrypoint: ./laravel_entrypoint.sh
        volumes:
          - .:/usr/src/app
        ports:
          - "5040:3000"
        environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=prueba123
          - POSTGRES_HOST=db
          - POSTGRES_DB=test_development